version: '3.7'

services:
  udmdrf:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: udmdrf
    container_name: udmdrf
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      TZ: 'Europe/Berlin'
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_PASSWORD: 'CHANGEME'
      DJANGO_SUPERUSER_EMAIL: 'admin@example.com'
