version: '3.9'

services:
  app:
    build:
      context: ./
    volumes:
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      TZ: 'Europe/Berlin'
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
