---
name: Checks

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: DJANGO_SETTINGS_MODULE='core.settings.settings' docker-compose run --rm app sh -c "python manage.py migrate && python manage.py test"
